### ISSUE TITLE
ToC issues

### ISSUE THREAD

**Issue by drgrigg** [michael-77/jonathan-swift_gullivers-travels#2]
I think you could leave out the z3998:letter from the Preface entry in the Landmarks.

And there's an error in the title of the LoI: Should be List of Illustrations (not Illustration, even though there's only one).

Also, we've tended to use the naming format illustration-1.svg, etc, not image-1.svg.

**Comment by michael-77** [comment]
I'm not seeing `z3998:letter` in the landmarks in `toc.xhtml`.

Are you meaning to remove it from the `<section>` tag within `preface.xhtml` itself?

The List of Illustrations is resolved in 9667e05

The change to illustration-1 resolved in f01277f

**Comment by drgrigg** [comment]
> Are you meaning to remove it from the <section> tag within preface.xhtml itself?

I was; but I think I've changed my mind. But it would look odd (and unnecessary) in the landmarks in ToC, so even if print-toc tries to put it in there, I would manually remove it from the ToC if so.
