### ISSUE TITLE
Unsemanticated <i> tags in endnotes

### ISSUE THREAD

**Issue by drgrigg** [michael-77/jonathan-swift_gullivers-travels#3]
I'm not sure why the name Sir W. Scott needs to be tagged as italics, though I imagine you've taken that from the Gutenberg transcription. 

I couldn't check it in the page scans, because that edition doesn't have any footnotes. 

I personally would just drop the `<i>` tags here.

**Comment by michael-77** [comment]
I've removed the `<i>` tags and added in `<abbr class="name">` which I'd managed to omit!
