### ISSUE TITLE
local.css issue

### ISSUE THREAD

**Issue by drgrigg** [michael-77/jonathan-swift_gullivers-travels#4]
I'm not quite sure why it's necessary to have a one-off CSS selector for the Latin quote in chapter-4-12. Why not simply bracket the text with `<i xml:lang="la'>` and be done with it?

**Comment by michael-77** [comment]
I wanted to signify that the whole of the blockquote is in Latin. 

The alternative gets into an inline element surrounding what are essentially two block level elements (disguised as a `<span>`) or having each line with an `<i>` of its own neither of which I'm a particular fan of.

**Comment by drgrigg** [comment]
Hmmm, I've been looking through other books, and the most common approach seems to be tagging each line with the appropriate language tag.

See Kate Chopin's Short Fiction, for example, but there are many others which adopt the same approach:

```
<blockquote epub:type="z3998:song">
	<p>
		<span>“<i xml:lang="fr">Lisett’ to kité la plaine,</i></span>
		<br/>
		<span>
			<i xml:lang="fr">Mo perdi bonhair à moué;</i>
		</span>
		<br/>
		<span>
			<i xml:lang="fr">Ziés à moué semblé fontaine,</i>
		</span>
		<br/>
		<span><i xml:lang="fr">Dépi mo pa miré toué.</i>”</span>
	</p>
</blockquote>
```
There are admittedly a few books which put the language tag into the blockquote, which I agree is neater, but there doesn't seem to be matching CSS to make the quote italic (see Maurice Leblanc's 815, chapter 14 for example).

@acabal, can you weigh in on this? Do we need to set a standard in the Poetry section for how to handle foreign language quotes?

**Comment by acabal** [comment]
I think the problem in the past was that it was unclear how to target `xml:lang` in CSS for italics, because it required a namespace declaration. Now `se lint` checks for that, so I think putting the language tag at the highest possible level is the best approach. Tweaking past productions can be a long-term project for the future. Maybe something to work on automating, on a slow day.

**Comment by drgrigg** [comment]
I guess the meta-question is whether whole foreign-language quotes need to be in italic at all. In-line foreign phrases (unless they have become anglicised) yes, there's a need to italicise them. But if the author is quoting great slabs of German or French, do they need to be in italics, too? I'm not sure that they do. This seems to be what Robin has been doing in his productions (that is, putting xml:lang into the blockquote but not having any CSS targeting that).

**Comment by acabal** [comment]
They should be, yes. All non-English text gets italics unless it's literally like multiple paragraphs, then we can look at it on a case-by-case basis.

**Comment by drgrigg** [comment]
In that case, Michael's approach in the CSS is correct and should be the standard?

```
blockquote[xml|lang]{
	font-style: italic;
}
```

**Comment by drgrigg** [comment]
Let's leave it as it is, then.
